version: "3.3"
services:
  user_service:
    image: quay.io/keycloak/keycloak:22.0.1
    ports:
      - 8090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      # KEYCLOAK_USER: admin
      # KEYCLOAK_PASSWORD: admin
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm.json
    entrypoint: ["/opt/keycloak/bin/kc.sh", "start-dev", "--import-realm"]
    # entrypoint: ["/opt/keycloak/bin/kc.sh", "start-dev", "--http-relative-path=/auth"] #, "--hostname=0.0.0.0", "--hostname-port=8080"]
    # entrypoint: ["/opt/keycloak/bin/kc.sh", "start", "--optimized", " --hostname-port=8080"]